repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: no-go-testing
      - id: golangci-lint
      - id: go-unit-tests
      # - id: validate-toml
  - repo: local
    hooks:
      - id: shfmt
        name: Format shell scripts
        entry: shfmt -w -i 4
        language: system
        types: [shell]
        require_serial: true

      - id: shellcheck
        name: Check shell scripts
        entry: shellcheck
        language: system
        types: [shell]
        require_serial: true
